### ISSUE TITLE
New command request - !boost @user

### ISSUE THREAD

**Issue by singhayushh** [DSCKGEC/community-discord-bot#2]
Hello 👋🏼,
We currently need some commands for our bot and contributions are welcome!
> We would be listing each required command in separate issues for convenience.

**Command Syntax**
`!boost @user`

**What would this command do?**
It would simply add a role (ID 755165816340611182) to the user mentioned.

**Who can use this command?**
Only users having a role named `Core Member` (see the [checkAuth](https://github.com/DSCKGEC/community-discord-bot/blob/master/message_handling/commands/checkAuth.js) command for reference)

> Please check for linked PRs and comments before contributing

**Comment by InternetRamen** [comment]
I am working on 1, 2, and 3. Can I be assigned this issue?

**Comment by Kryze** [comment]
Hello I've already done the 1 and was about to post it, is that a problem ? :)

**Comment by singhayushh** [comment]
@InternetRamen and @Kryze 
Please make sure you don't end up working on the same section!
Contributions to any of those required commands are welcome :)

**Comment by Kryze** [comment]
I've started to work on the first one before posting here, but I could finish it and post it on October 1st for Hacktoberfest ?

**Comment by InternetRamen** [comment]
@Kryze I can do 2 and 3 then.

**Comment by InternetRamen** [comment]
I'm not sure if the PR I finished count toward Hacktoberfest 2020. #3 However, I finished both commands!

**Comment by singhayushh** [comment]
As long as it is not marked as spam (be assured it wont!), your PR does seem to qualify for a valid PR.
Your PR will be merged once tested and reviewed.

Thank you for your valuable contributions. ❤️ 
Stay tuned!

**Comment by InternetRamen** [comment]
@singhayushh Glad I could help.

Could I also work on number 5?

**Comment by singhayushh** [comment]
It would be better if you could wait for the PR #3 to get reviewed by our team once before you make further additions.
Also, I'd ask you to raise issues for any ideas you get for point 6, even if you wouldn't prefer to code it out!

**Comment by InternetRamen** [comment]
> It would be better if you could wait for the PR #3 to get reviewed by our team once before you make further additions.
> 
> Also, I'd ask you to raise any ideas you get for point 6 as issues, even if you wouldn't prefer to code it out! 
> 
> 
 I understand. I will try thinking of ideas as well.

**Comment by singhayushh** [comment]
This is to notify that all 6 commands listed in this issue will be moved to separate individual issues so that it would be easier for people to know which all issues have been resolved. 

Thank you.
