### ISSUE TITLE
New Command Request - new user entry

### ISSUE THREAD

**Issue by singhayushh** [DSCKGEC/community-discord-bot#7]
Hello 👋🏼,
We currently need some commands for our bot and contributions are welcome!
> We would be listing each required command in separate issues for convenience.

**Command Syntax**
-- none --
This command would be triggered whenever a new user joins the server

**What would this command do?**
Whenever a new user joins, the bot is triggered to DM the user asking for his name and college / institution. If the user's college is `KGEC` or `Kalyani Government Engineering College`, he would be assiged role (ID - 760660088582438967) by the bot.

**Who can use this command?**
-- none --
Triggered whenever a new user joins the server

**Comment by dineshsy** [comment]
Hey @singhayushh  :peace_symbol: .. I would like to work on this issue..!!

**Comment by singhayushh** [comment]
Sure!
We had recently been contacted by another dev, who was willing to contribute to this issue, 
@InternetRamen, please have your say.

**Comment by InternetRamen** [comment]
@dineshsy @singhayushh I am willing to help contribute with this issue. Do you have any tasks for us or me?

**Comment by dineshsy** [comment]
ok no issues @InternetRamen . You take this from now onwards <3

**Comment by InternetRamen** [comment]
@dineshsy Alright, thanks!

**Comment by InternetRamen** [comment]
@singhayushh Should I just code on my fork or should I get a new copy of the develop branch?

**Comment by singhayushh** [comment]
I was currently testing your changes.
Would merge the PR soon if everything runs fine, as it is running.
So it is totally upto you whether you want to wait and issue a new PR or keep adding to the existing one.

**Comment by InternetRamen** [comment]
#10
