### ISSUE TITLE
New Command Request - !clist-live and !clist-up

### ISSUE THREAD

**Issue by singhayushh** [DSCKGEC/community-discord-bot#8]
Hello 👋🏼,
We currently need some commands for our bot and contributions are welcome!
> We would be listing each required command in separate issues for convenience.

**Command Syntax**
`!clist-live` and `!clist-up`

**What would this command do?**
This command would trigger the bot to scrape the site [clist.by](https://clist.by) for the live and upcoming contests and return the same as an embed message.

**Who can use this command?**
Everyone.

> Please use [cheerio](https://www.npmjs.com/package/cheerio) and [request](https://www.npmjs.com/package/request) only for scraping

**Comment by AyushmanBilasThakur** [comment]
Working on this, want to learn cheerio as well as commit

**Comment by AyushmanBilasThakur** [comment]
Do this command need to extract the subcontests or the contests only?

**Comment by AyushmanBilasThakur** [comment]
@singhayushh Have a look 😅

**Comment by singhayushh** [comment]
Sure. 
It'd be better to limit it to contests instead of sub contests as well 
But that can definitely be done later.
