### ISSUE TITLE
Bot command ideas thread

### ISSUE THREAD

**Issue by singhayushh** [DSCKGEC/community-discord-bot#9]
Hello, 
We @DSCKGEC are currently developing a discord bot for our server.
While still in budding stages of development, we are open to ideas for our bot.

#### About the server
This server is targeted at minimizing distances between different communities and members. It would be the mecca of communication, reaching a wide audience and helping communities grow, learn and work together. The main motive of our server is to allow community members and developers to collaborate with each other easily, make community projects, grow their networks and skill-set in a wonderful and motivating environment.

#### About the bot
Our discord bot would play a vital role in managing the server, making things swifter and easier by providing a wide range of features from assigning requested roles to members to providing latest news and events feed across all domains of technology.

We are open to ideas for the development of the bot - its features, commands and functionalities.
Any suggestions are welcome, including a name or display picture for the bot. Use this issue as a thread to drop in any ideas or suggestions you may have!

> We would be making the server public soon 👀

**Comment by aritra-sarkar99** [comment]
I want to add a feature to the bot which keeps count of the number of members in the server.

**Comment by singhayushh** [comment]
Sure @aritra-sarkar99 
If you'd want to contribute yourself, I can create a new issue for this and assign it to you.

**Comment by aritra-sarkar99** [comment]
Yes @singhayushh  , please do so.
